on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      deployments: write
    name: Deploy to Cloudflare Hosting
    env:
      ## Sets environment variable
      NODE_ENV: "main"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run:  npm install

      - name: Build
        run: |
          npm run build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: api-saas-app
          directory: dist/api-monetization/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
