name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run compodoc

      - name: Deploy to GitHub Pages
        run: |
          mkdir gh-pages
          cp -r documentation/* gh-pages
          git checkout --orphan gh-pages
          git --work-tree=gh-pages add --all
          git --work-tree=gh-pages commit -m "Deploy documentation to GitHub Pages"
          git push origin HEAD:gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
