name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "pmutua@automation.io"
          git config --global user.name "pmutua"

      - name: Deploy to GitHub Pages
        run: |
          mkdir gh-pages
          cp -r documentation/* gh-pages
          git checkout --orphan gh-pages
          git --work-tree=gh-pages add --all
          git --work-tree=gh-pages commit -m "Deploy documentation to GitHub Pages"
          git push origin HEAD:gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
